import { Kumbh_Sans } from "next/font/google";
import "./global.css";

import { Toaster } from "react-hot-toast";
import SmoothScrollProvider from "./_components/_smoothProvider/SmoothScrollProvider";
import { CartProvider } from "./_context/CartContext";
import Header from "./_components/_header/Header";
import Footer from "./_components/_footer/Footer";
import { NavColorProvider } from "./_context/NavColorContext";

const kumbhSans = Kumbh_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Sneakers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${kumbhSans.className} relative antialiased mx-auto text-dark-500`}
      >
        <CartProvider>
          <Header />
          <SmoothScrollProvider>
            {children}
            <Footer />
          </SmoothScrollProvider>
        </CartProvider>

        <Toaster position="top-center" />
      </body>
    </html>
  );
}
