import { Kumbh_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "@/app/global.css";

const kumbhSans = Kumbh_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Sneakers",
  description: "Generated by create next app",
};

export default function SignUpRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${kumbhSans.className} relative antialiased mx-auto text-dark-500`}
      >
        <main className="w-full min-h-screen">{children}</main>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
