import Footer from "@/_components/_footer/Footer";
import "@/app/global.css";
import { Kumbh_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Header from "../../_components/_header/Header";
import SmoothScrollProvider from "../../_components/_smoothProvider/SmoothScrollProvider";
import { CartProvider } from "../_context/CartContext";
import QueryProvider from "@/_components/query-provider/QueryProvider";
import { ReactNode } from "react";
import { Metadata } from "next";

const kumbhSans = Kumbh_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sneakers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${kumbhSans.className} relative antialiased mx-auto text-dark-500 bg-slate-50`}
      >
        <CartProvider>
          <Header />
          <QueryProvider>
            <SmoothScrollProvider>
              <main className="w-full min-h-screen">{children}</main>
              <Footer />
            </SmoothScrollProvider>
          </QueryProvider>
        </CartProvider>

        <Toaster position="top-center" />
      </body>
    </html>
  );
}
